// Datos para el ejido Las Delicias
let propiedades = [
    {
      posesionario: "Saul Alberto Ruiz Ruvalcaba",
      manzanaRAN: "05",
      solarRAN: "30",
      manzanaEjido: "10A",
      solarEjido: "15",
      superficie: "1000 m2",
      ubicacion: "Colonia San Isidro",
      direccion: "Calle 5 de Febrero #123",
      estatus: "En proceso",
    },
    {
      posesionario: "Violeta Ruiz Robles",
      manzanaRAN: "04",
      solarRAN: "49",
      manzanaEjido: "12B",
      solarEjido: "22",
      superficie: "1250 m2",
      ubicacion: "Colonia San Isidro",
      direccion: "Calle Hidalgo #45",
      estatus: "Privado",
    },
    {
      posesionario: "Angelica Huerta Acosta",
      manzanaRAN: "02",
      solarRAN: "35",
      manzanaEjido: "10A",
      solarEjido: "18",
      superficie: "950 m2",
      ubicacion: "Colonia Centro",
      direccion: "Avenida Principal #88",
      estatus: "Terminado",
    },
    {
      posesionario: "Saul Alberto Ruiz Ruvalcaba",
      manzanaRAN: "05",
      solarRAN: "30",
      manzanaEjido: "10A",
      solarEjido: "15",
      superficie: "1000 m2",
      ubicacion: "Colonia San Isidro",
      direccion: "Calle 5 de Febrero #123",
      estatus: "En proceso",
    },
    {
      posesionario: "Violeta Ruiz Robles",
      manzanaRAN: "04",
      solarRAN: "49",
      manzanaEjido: "12B",
      solarEjido: "22",
      superficie: "1250 m2",
      ubicacion: "Colonia San Isidro",
      direccion: "Calle Hidalgo #45",
      estatus: "Privado",
    },
    {
      posesionario: "Angelica Huerta Acosta",
      manzanaRAN: "02",
      solarRAN: "35",
      manzanaEjido: "10A",
      solarEjido: "18",
      superficie: "950 m2",
      ubicacion: "Colonia Centro",
      direccion: "Avenida Principal #88",
      estatus: "Terminado",
    },
    {
      posesionario: "Saul Alberto Ruiz Ruvalcaba",
      manzanaRAN: "05",
      solarRAN: "30",
      manzanaEjido: "10A",
      solarEjido: "15",
      superficie: "1000 m2",
      ubicacion: "Colonia San Isidro",
      direccion: "Calle 5 de Febrero #123",
      estatus: "En proceso",
    },
    {
      posesionario: "Violeta Ruiz Robles",
      manzanaRAN: "04",
      solarRAN: "49",
      manzanaEjido: "12B",
      solarEjido: "22",
      superficie: "1250 m2",
      ubicacion: "Colonia San Isidro",
      direccion: "Calle Hidalgo #45",
      estatus: "Privado",
    },
    {
      posesionario: "Angelica Huerta Acosta",
      manzanaRAN: "02",
      solarRAN: "35",
      manzanaEjido: "10A",
      solarEjido: "18",
      superficie: "950 m2",
      ubicacion: "Colonia Centro",
      direccion: "Avenida Principal #88",
      estatus: "Terminado",
    },
    {
      posesionario: "Saul Alberto Ruiz Ruvalcaba",
      manzanaRAN: "05",
      solarRAN: "30",
      manzanaEjido: "10A",
      solarEjido: "15",
      superficie: "1000 m2",
      ubicacion: "Colonia San Isidro",
      direccion: "Calle 5 de Febrero #123",
      estatus: "En proceso",
    },
    {
      posesionario: "Violeta Ruiz Robles",
      manzanaRAN: "04",
      solarRAN: "49",
      manzanaEjido: "12B",
      solarEjido: "22",
      superficie: "1250 m2",
      ubicacion: "Colonia San Isidro",
      direccion: "Calle Hidalgo #45",
      estatus: "Privado",
    },
    {
      posesionario: "Angelica Huerta Acosta",
      manzanaRAN: "02",
      solarRAN: "35",
      manzanaEjido: "10A",
      solarEjido: "18",
      superficie: "950 m2",
      ubicacion: "Colonia Centro",
      direccion: "Avenida Principal #88",
      estatus: "Terminado",
    },
];
